name: circular_carousel
description: A custom circular carousel.
repository: https://github.com/frybitsinc/circular_carousel
homepage: https://github.com/frybitsinc/circular_carousel
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/glb/
  uses-material-design: true
